### ISSUE TITLE
You could reduce your DUB example header from 11 lines to three lines

### ISSUE THREAD

**Issue by wilzbach** [henrygouk/dopt#1]
Hey I just looked at your nice library and while browsing the examples I saw this monster:

```json
/+
dub.json:
{
    "name": "cifar10",
    "dependencies": {
        "dopt": {
            "path": "../"
        }
    }
}
+/
```

Are you it could be as simple as?

```d
/+ dub.sdl:
dependency "dopt" path=".."
+/
```

**Comment by henrygouk** [comment]
Thanks for pointing this out! I had never been a big fan of the verbosity there. This has been changed in 24a9f9b
