### ISSUE TITLE
Examples don't work on AMD CPU

### ISSUE THREAD

**Issue by WebFreak001** [henrygouk/dopt#5]
cat /pr`4.14.11-1-ARCH`
```
./cifar10.d cifar-10-batches-bin/
object.Exception@../source/dopt/core/cpu/package.d(200): No CPU kernel registered for operation uniform
----------------
??:? dopt.core.types.Buffer[] dopt.core.cpu.evaluateCPU(dopt.core.ops.Operation[], dopt.core.types.Buffer[dopt.core.ops.Operation]) [0xf4c3bbbc]
??:? void dopt.core.cpu.CPUPlan.executeImpl(dopt.core.types.Buffer[dopt.core.ops.Operation], dopt.core.types.Buffer[]) [0xf4c3b067]
??:? void dopt.core.Plan.execute(dopt.core.types.Buffer[dopt.core.ops.Operation], dopt.core.types.Buffer[]) [0xf4c34dee]
??:? dopt.core.types.Buffer[] dopt.online.adam.adam(dopt.core.ops.Operation[], dopt.core.ops.Operation[], dopt.core.ops.Operation delegate(dopt.core.ops.Operation)[dopt.core.ops.Operation], dopt.core.ops.Operation, dopt.core.ops.Operation, dopt.core.ops.Operation, dopt.core.ops.Operation).update(dopt.core.types.Buffer[dopt.core.ops.Operation]) [0xf4c385b9]
??:? _Dmain [0xf4c1c184]
Program exited with code 1
```

```
AMD Ryzen 7 1700X Eight-Core Processor
```

It hangs for a really long time without any output and then just outputs that. Didn't check the other example because it hangs for an eternity too

**Comment by henrygouk** [comment]
Unfortunately a lot of the neural network operations aren't implemented for CPU. This is something I intend to implement in the future, but there is no timeframe for this yet.

**Comment by henrygouk** [comment]
What I can do is create another example that is possible to run on the CPU. E.g. a logistic regression model on MNIST.

**Comment by WebFreak001** [comment]
uh but this didn't work on my AMD Radeon RX 480 either (well OpenCL instead of CUDA there)

Have you maybe considered using opencl (or the [DCompute](https://dlang.org/blog/2017/07/17/dcompute-gpgpu-with-native-d-for-opencl-and-cuda/) thing there on ldc)? And maybe also [mir](https://github.com/libmir/mir-glas) instead of blas

**Comment by p0nce** [comment]
You would have to write/debug the OpenCL kernels that are already there in cuDNN I guess.

**Comment by 9il** [comment]
> Have you maybe considered using opencl (or the DCompute thing there on ldc)? And maybe also mir instead of blas

added issues #6 #7

**Comment by WebFreak001** [comment]
separating this into these two seems like a good idea
